# Generated by Django 4.0.6 on 2022-07-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Inprocess', 'Inprocess'), ('Prepared', 'Prepared'), ('On_the_way', 'On_the_way'), ('Delevered', 'Delevered')], default='Pending', max_length=20)),
                ('size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extraLarge', 'extraLarge')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('toppings', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=10)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
